### ISSUE TITLE
Should be using flexbox instead

### ISSUE THREAD

**Issue by georgebutter** [Elkfox/Focus#2]
The popups are using -50% transforms to center them. This sometimes means that they, and  their contents are placed on a subpixel value which causes blurriness. There are hacks to resolve this but it varies across browsers and hardware.

Seems as though flexbox is the only pure css solution to this issue.

![image](https://user-images.githubusercontent.com/930712/32303932-cdde8196-bfbf-11e7-9b7b-ce9f093c4bdb.png)
![image](https://user-images.githubusercontent.com/930712/32303935-d8de5d82-bfbf-11e7-8101-9fcf13fe14a2.png)

**Comment by cam** [comment]
If we want to avoid flex box for now, we can use that table method for pure-css vertical alignment that is 100% backward compatible.

**Comment by georgebutter** [comment]
Yeh flex box isn't supported at all by IE 9, and has a few issues on 10 and 11. Does the table method not create this sub pixel blurring?

**Comment by cam** [comment]
It shouldn't no, as it doesn't use any translates. One issue with removing translates is that we are potentially more limited in terms of the positioning and animation options that are possible.

I did have the blurriness this covered in one of my early iterations pre Concrete/Reinforced, so we may be best of investigating that again.

**Comment by georgebutter** [comment]
Have tested the table method in a codepen and it does work, at least for fonts. But have not idea how we will handle the animations.

**Comment by cam** [comment]
@ButsAndCats OK, great. I feel like that a good sign. We may as well try that out for the outer container. The animations use negative margins for transitions moving to the 0 position, so that _should_ be OK.

**Comment by oscarstranger** [comment]
Added flex in v1.5
