### ISSUE TITLE
data-trigger events

### ISSUE THREAD

**Issue by oscarstranger** [Elkfox/Focus#3]
The popups trigger event listens for all elements with `[data-trigger]` instead of  `[data-trigger="popup"]` which can disable other unrelated functions that might want to use the data-trigger attribute (such as: `data-trigger="toggle"` or `data=trigger="my-unrelated-trigger"`)

The trigger line should be updated as follows:
~~`jQuery(document).on('click', '[data-trigger]', function(event) {`~~
`jQuery(document).on('click', '[data-trigger="popup"]', function(event) {`

**Comment by georgebutter** [comment]
done!
